# jvm args for gradle build
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
# enable/disable using transitive R classes
android.nonTransitiveRClass=true
# enable/disable parallel build
org.gradle.parallel=true
# enable/disable configure on demand
org.gradle.configureondemand=true
# enable/disable build cache
org.gradle.caching=true
# enable/disable Gradle configuration cache
org.gradle.configuration-cache=true
# enable/disable Gradle daemon
org.gradle.daemon=true
# enable/disable watching file system
org.gradle.vfs.watch=true
# enable/disable BuildConfig class generating
android.defaults.buildfeatures.buildconfig=false
# enable/disable AIDL compilation (for multiprocess)
android.defaults.buildfeatures.aidl=false
# enable/disable RenderScript support (for computing and processing photo with CPU and GPU)
android.defaults.buildfeatures.renderscript=false
# enable/disable Shaders
android.defaults.buildfeatures.shaders=false
# enable/disable using of final id-s for resources
android.nonFinalResIds=true
# enable/disable Jetifier
android.enableJetifier=false
# Other settings
kotlin.code.style=official
android.useAndroidX=true